use_frameworks!
target 'FireStream Demo' do
  pod 'FireStream', :path => '../'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'

end

target 'FireStream_Tests' do
  pod 'FireStream', :path => '../'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  
end
